version: '3'

services:
  mysqldb:
    build: 
      context: ./mysql
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=test123
  mosquitto:
    build: 
      context: ./mosquitto
      args:
        - auth_backend=MYSQL
    container_name: mosquitto
    depends_on:
      - mysqldb
