version: '3'

services:
  postgres:
    build: 
      context: ./postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=test123
  mosquitto:
    build: 
      context: ./mosquitto
      args:
        - auth_backend=POSTGRES
    container_name: mosquitto
    depends_on:
      - postgres
    ports:
      - "8883:8883"
